# Server Port
server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# Database Configuration (H2)
spring.datasource.url=jdbc:h2:file:./campus_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# View configuration for SPA routing fallback
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html

# Mail Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kurubarakesh47@gmail.com
spring.mail.password=qkxe nceq pmjt hczj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
